# Übungsaufgabe 1: Array-Erstellung
Erstelle ein NumPy-Array mit den Werten [1, 2, 3, 4, 5].

In [1]:
import numpy as np
array_1 = np.array([1, 2, 3, 4, 5])
print(array_1, type(array_1))

[1 2 3 4 5] <class 'numpy.ndarray'>


# Übungsaufgabe 2: Array-Operationen
## Gegeben das Array [1, 2, 3, 4, 5], führe folgende Operationen aus:
### a) Multipliziere alle Elemente mit 2.
### b) Quadriere alle Elemente.
### c) Berechne die Summe aller Elemente.
### d) Finde den maximalen Wert im Array.

In [2]:

array_1 = np.array([1, 2, 3, 4, 5])
print('array_1: ', array_1)

# a) Multipliziere alle Elemente mit 2.
print('2 x multiplied array :', array_1*2)

# b) Quadriere alle Elemente.
squared_array = np.square(array_1)
print('squared_array: ', squared_array)


# c) Berechne die Summe aller Elemente.
print('sum_array: ', array_1.sum())

# d) Finde den maximalen Wert im Array.
print('maximal_value ', array_1.max())



array_1:  [1 2 3 4 5]
2 x multiplied array : [ 2  4  6  8 10]
squared_array:  [ 1  4  9 16 25]
sum_array:  15
maximal_value  5


# Übungsaufgabe 3: Array-Indizierung und -Slicing
Gegeben das Array [1, 2, 3, 4, 5], führe folgendes aus:

a) Rufe das Element an Index 2 ab.

b) Rufe die Elemente von Index 1 bis 3 ab.

c) Rufe die letzten beiden Elemente ab.

In [3]:
a = np.array([1, 2, 3, 4, 5])
print('array_1: ', array_1)

# a) Rufe das Element an Index 2 ab.
print(a[2])

# b) Rufe die Elemente von Index 1 bis 3 ab.
print(a[1:3])

# c) Rufe die letzten beiden Elemente ab.
print(a[-2:])

array_1:  [1 2 3 4 5]
3
[2 3]
[4 5]


# Übungsaufgabe 4: Arrays umformen (Reshaping)
Gegeben das Array [[1, 2, 3], [4, 5, 6]], forme es in ein 3x2-Array um.


In [4]:

b = np.array([[1, 2, 3], [4, 5, 6]])
print('original_array: \n', b)
print()
c = b.reshape(3, 2)
print('array_reshaped: \n', c)


original_array: 
 [[1 2 3]
 [4 5 6]]

array_reshaped: 
 [[1 2]
 [3 4]
 [5 6]]


# Übungsaufgabe 5: Array-Aggregation
Gegeben das Array [[1, 2, 3], [4, 5, 6]], berechne folgendes:

a) Berechne den Mittelwert aller Elemente.

b) Berechne die Summe jeder Spalte.

c) Berechne das Produkt jeder Zeile.

In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print('original_array: \n', b)
print()

# a) Berechne den Mittelwert aller Elemente.
print('mean: ', np.mean(b))

# b) Berechne die Summe jeder Spalte ('stolbetc/row').
print('sum: ', np.sum(b, axis=0))

# c) Berechne das Produkt jeder Zeile ('stroka/column').
print('product: ', np.prod(b, axis=1))


original_array: 
 [[1 2 3]
 [4 5 6]]

mean:  3.5
sum:  [5 7 9]
product:  [  6 120]


# Übungsaufgabe 6: 
Gegeben die Arrays [1, 2, 3] und [4, 5, 6], addiere sie 

In [44]:
a = np.array([1,2,3]) 
b = np.array([4,5,6])
c = a + b
print(c)

[5 7 9]


# Übungsaufgabe 7: Array-Filterung
Gegeben das Array [1, 2, 3, 4, 5], filtere die Elemente heraus, die größer als 3 sind.

In [46]:

a = np.array([1, 2, 3, 4, 5])
print(a[a>3])


[4 5]


# Übungsaufgabe 8: Array-Sortierung
Gegeben das Array [5, 3, 1, 4, 2], sortiere es in aufsteigender Reihenfolge.

In [49]:

c = np.array([5, 3, 1, 4, 2])
print('original array :', c)

c.sort()
print('sorted array :', c)

original array : [5 3 1 4 2]
sorted array : [1 2 3 4 5]


# Übungsaufgabe 9: Arrays stapeln (Stacking)
Gegeben die Arrays [1, 2, 3] und [4, 5, 6], stapel sie vertikal.

In [57]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked_array = np.vstack((a, b))
print('stacked_array: \n', stacked_array)


stacked_array: 
 [[1 2 3]
 [4 5 6]]


# Übungsaufgabe 10: Zufallszahlenerzeugung
Erzeuge eine 3x3-Matrix mit Zufallszahlen zwischen 0 und 1.

In [60]:

d = np.random.random((3,3))
print('3x3 matrix with random numbers between 0 und 1: \n', d)


3x3 matrix with random numbers between 0 und 1: 
 [[0.74993879 0.05747027 0.26823077]
 [0.87196573 0.91590852 0.02344137]
 [0.75970338 0.57898413 0.35674817]]
