# Numpy



In [ ]:
# pip install numpy

In [2]:
import numpy as np

In [3]:
import sys
import time

# Compare native Python List with Numpy
1. Memory Size
2. Time 


In [4]:
SIZE = 100
# Create a Python List with 100x intergers
mylist = range(SIZE)
print(sys.getsizeof(5)) # size of e integer in Python : 28 Byte
print(sys.getsizeof(5) * SIZE) # size of 100 integer in Python : 2800 Byte

28
2800


In [5]:
# Create a Numpy Array
numpy_array = np.arange(SIZE)
print(numpy_array.itemsize) # size of an integer in a numpy: 4 bytes 
print(numpy_array.itemsize * SIZE) # size of 100 integer in a numpy: 400 bytes 

4
400


In [6]:
SIZE = 1000000

# Create Python Lists
mylist1 = range(SIZE)
mylist2 = range(SIZE)

start_time = time.time()
result = [(x+y) for x, y in zip(mylist1, mylist2)] # sum between mylist1 and mylist2
end_time = time.time()
print('Python Time ', (end_time - start_time) * 1000) # 1000 for the precision

Python Time  85.01935005187988


In [7]:
SIZE = 1000000

# Create Numpy Arrays
array1 = np.arange(SIZE)
array2 = np.arange(SIZE)

start_time = time.time()

result = array1 + array2

end_time = time.time()

print('Python Time ', (end_time - start_time) * 1000) # 1000 for the precision

Python Time  10.001420974731445


# Define Arrays

In [8]:
# 1 - via a python native list
mylist = [1, 2, 3, 4, 5]
print(mylist, type(mylist))

array = np.array(mylist)
print(array, type(array))

# 2. Define directly one one dimensional array
array_1 = np.array([23, 34, 56, 78])
print(array_1, type(array_1))

# 2. Define multi dimensional array
array_2 = np.array([[1, 2], [3, 4]])
print(array_2, type(array_2))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>
[23 34 56 78] <class 'numpy.ndarray'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [9]:
# Define with specific data Types

array_1 = np.array([23, 34, 56, 78], dtype = np.float64)
print(array_1, type(array_1))

array_2 = np.array([[1, 2], [3, 4]], dtype = np.int32)
print(array_2, type(array_2))

array_3 = np.array([[1, 2], [3, 4]], dtype = np.complex_)
print(array_3, type(array_2))

[23. 34. 56. 78.] <class 'numpy.ndarray'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]] <class 'numpy.ndarray'>


# Array Information

In [10]:
# 2. Define directly one dimensional array

array_1 = np.array([23, 34, 56, 78])
print(array_1, type(array_1))

print(array_1.ndim) # 1
print(array_1.shape) # (4, )
print(array_1.size) 
print(array_1.dtype)
print(array_1.itemsize) # 4 * Bytes

[23 34 56 78] <class 'numpy.ndarray'>
1
(4,)
4
int32
4


In [11]:
# Multi dimensional Array
array_2 = np.array([[1, 2], [3, 4], [5, 6]])
array_2

print(array_2.ndim) # 2
print(array_2.shape) # (3, 2)
print(array_2.size) # 6
print(array_2.dtype) # int32
print(array_2.itemsize) # 4 * bytes

2
(3, 2)
6
int32
4



# Mathematical Operations

In [12]:
a = np.arange(10) # 0-9 
b = np.arange(1,11) # 1 - 10

print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

print(a+1)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0  2  6 12 20 30 42 56 72 90]
[0.         0.5        0.66666667 0.75       0.8        0.83333333
 0.85714286 0.875      0.88888889 0.9       ]
[ 1  2  3  4  5  6  7  8  9 10]


# Numpy Array Functions 

In [13]:
a = np.arange(10) # 0-9 
b = np.arange(1, 11) # 1 - 10
c = np.array( [[1, 2], 
               [3, 4],
               [5, 6]
              ]
              )

print(np.sqrt(a))

# Array Functions
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())

print(c.sum())

# Advanced Sum
"""
axis = 0 -> columns
axis = 1 -> rows
""" 
print(c.sum(axis = 0)) # column-wise [9, 12]
print(c.sum(axis = 1)) # row-wise [3, 7, 11]

# Sorting
a = np.array([5, 8, 3, 3, 2.123, 45, 100, 56.87, 0])
print('original a: ', a)
a.sort()
print('sorted a: ', a)

# Rounding
print('rounded a: ', a.round(decimals = 2))


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
45
0
9
4.5
21
[ 9 12]
[ 3  7 11]
original a:  [  5.      8.      3.      3.      2.123  45.    100.     56.87    0.   ]
sorted a:  [  0.      2.123   3.      3.      5.      8.     45.     56.87  100.   ]
rounded a:  [  0.     2.12   3.     3.     5.     8.    45.    56.87 100.  ]


# Accessing Items - > Slicing 

In [19]:
c = np.array([[1, 2], 
               [3, 4],
               [5, 6]])
print(c.shape)
print()

print(c[0]) # [1, 2]
print(c[1]) # [3, 4]
print(c[2]) # [5, 6]

print(c[-1]) # [5, 6]
print()

print(c[::-1])  # rückwärts
print()

# Specific Item (row, column)
print(c[1, 1]) # 4
print()

# Range of items
print(c[0:2, 0:2])

(3, 2)

[1 2]
[3 4]
[5 6]
[5 6]

[[5 6]
 [3 4]
 [1 2]]

4

[[1 2]
 [3 4]]


# Generate Data 


In [20]:
a = np.arange(30) # 0 -29
b = np.arange(10, 30) # 10-29
print(a)
print(b)

zeros = np.zeros((3, 4)) # only zeroes, 3x rows, 4x columns
print(zeros)

ones = np.ones((3, 4)) # only ones, 3x rows, 4x columns
print(ones)

number = np.full( (3, 4), 5) # fill the array with specific value (5), 3x rows, 4x columns 
print(number)

numbers_linspace = np.linspace(1, 10, 4) # 4 numbers between 1 and 10, equidistant
print('numbers_linspace: ', numbers_linspace)

# Indentit< Matrix
numbers = np.eye(5)
print(numbers)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
numbers_linspace:  [ 1.  4.  7. 10.]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Reshaping / Shaping 

In [6]:
import numpy as np
a = np.array([ [1,2],
               [3,4],
               [5,6]])

print()
print(a)
print()
print(a.shape)
print()

# 1. Reshape to 2x3

b = a.reshape(2,3)
print(b)
print()
print(b.shape)

# 2. Reshape to 6x1
print()
c = a.reshape(6, 1)
print(c)
print()
print(c.shape)

# 3. Reshape to a vector
print()
d = a.reshape(6, )
print(d)
print()
print(d.shape)
print()

# Alternative zu 3
# 4 Flatten
result = a.ravel()
print(result)
print()
print(result.shape)



[[1 2]
 [3 4]
 [5 6]]

(3, 2)

[[1 2 3]
 [4 5 6]]

(2, 3)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

(6, 1)

[1 2 3 4 5 6]

(6,)

[1 2 3 4 5 6]

(6,)


# Random 

In [8]:
from numpy import random

In [12]:
# a single random integer
x = random.randint(100)
print(x, type(x))
print()

# 1x dim random array with integers
x = random.randint(100, size=(5,))
print(x, type(x))
print()

# m x n random array with integers
x = random.uniform(100, size=(2,3))
print(x, type(x))
print()

# Create a numpy array with 10 random float values between 0 and 1
random_floats = np.random.rand(10)
print(random_floats)
print()

# Create a normal distribution with 50 random values
normal_distribution = np.random.normal(50, 10, size = 50)
print(normal_distribution)



67 <class 'int'>

[ 3 87 42 30 95] <class 'numpy.ndarray'>

[[95.63942912 25.05456923 94.83001274]
 [88.65087424 26.14048074 32.6711983 ]] <class 'numpy.ndarray'>

[0.78729708 0.14369471 0.91939156 0.39276138 0.4103295  0.99805395
 0.70182441 0.7294542  0.97140241 0.86274572]

[46.96172328 40.87036817 49.70239371 59.71602441 79.57043144 46.39390751
 45.80004186 39.75250721 47.26065201 51.01779531 50.6433184  45.86359692
 47.08734671 57.7051109  48.03525568 64.3411301  60.84448317 43.32221126
 44.55008302 51.29616916 61.56207324 63.22345313 49.70676861 59.76181337
 41.10355227 54.21060684 64.83806188 66.45505129 44.19681066 59.91177624
 40.1493174  54.4507867  43.37260223 56.44945304 40.43247144 53.08737639
 48.38548878 47.81853867 51.43668505 56.78800109 42.41429098 59.9088732
 44.60371252 31.46448291 38.24343851 54.24011883 46.98903727 40.14677184
 46.03557722 48.01808424]


In [13]:
# Choice
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# single choice
x = np.random.choice(my_list)
print(x)
print()

# 3 x choices
x = np.random.choice(my_list, size = (3,))
print(x)
print()

# [n x m ] choices
x = np.random.choice(my_list, size = (3, 2))
print(x)

1

[7 9 8]

[[4 3]
 [6 7]
 [3 3]]


# View

In [15]:
original = np.array([1, 2, 3, 4, 5])

view = original # this is just a view -> b will refer to the same container as a 

print(view)
print(original)
print()

# a change the original array
original[0] = 10
print(original)

# will produce a chamge in the view b
print(view)
print()

# a change in view will produce a change in the original variable
view[2] = 33
print(view)

print(original)

[1 2 3 4 5]
[1 2 3 4 5]

[10  2  3  4  5]
[10  2  3  4  5]

[10  2 33  4  5]
[10  2 33  4  5]


# Copy

In [16]:
original = np.array([1, 2, 3, 4, 5])
copied = original.copy() # create different container with the same view

print(original)
print(copied)
print()

original[1] = 100
print(original)
print(copied)
print()

copied[-1] = 1000
print(copied)
print(original)

[1 2 3 4 5]
[1 2 3 4 5]

[  1 100   3   4   5]
[1 2 3 4 5]

[   1    2    3    4 1000]
[  1 100   3   4   5]


# Vertical Stack 

In [17]:
a = np.array([ [1, 2],
               [3, 4],
               [5, 6]])


b = np.array([ [11, 22],
               [33, 44],
               [55, 66]])

result = np.vstack( (a, b)) # Vertical Stacking
result


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 22],
       [33, 44],
       [55, 66]])

# Horizontal Stacking

In [18]:
a = np.array([ [1, 2],
               [3, 4],
               [5, 6]])


b = np.array([ [11, 22],
               [33, 44],
               [55, 66]])

result = np.hstack( (a, b)) # Horizontal Stacking
result

array([[ 1,  2, 11, 22],
       [ 3,  4, 33, 44],
       [ 5,  6, 55, 66]])

# Transpose()

In [19]:
a = np.array([ [1, 2],
               [3, 4],
               [5, 6]])

print(a)
print()

result = a.T # Transpose
print(result)

[[1 2]
 [3 4]
 [5 6]]

[[1 3 5]
 [2 4 6]]


# Where()

In [20]:
a = np.array([1,2,3,4,5])
b = np.array([10,3,2,4,5])

# The position where a == b
print(np.where(a == b))



(array([3, 4], dtype=int64),)
